version: '3.2'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - /films/node_modules
      - .:/films
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /nextserver/node_modules
      - .:/nextserver
    depends_on:
      - mysql_server
    links:
      - mysql_server

  mysql_server:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=notes_db
      - MYSQL_USER=nrjshka
      - MYSQL_PASSWORD=myTestPassword
      - MYSQL_ROOT_PASSWORD=myTestPassword
      - DB_HOST=mysql_server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql_server
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql_server
      MYSQL_ROOT_PASSWORD: myTestPassword

volumes:
  db_data:
