version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - .:/src/node_modules
    depends_on:
      - mysql_server
    networks:
      - notes_network

  mysql_server:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '127.0.0.1:3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=notes_db
      - MYSQL_USER=nrjshka
      - MYSQL_PASSWORD=myTestPassword
      - MYSQL_ROOT_PASSWORD=myTestPassword
    networks:
      - notes_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql_server
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql_server
      MYSQL_ROOT_PASSWORD: myTestPassword
    networks:
      - notes_network

networks:
  notes_network:

volumes:
  db_data:
