version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - .:/src/node_modules
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=notes_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=myTestPassword
      - MYSQL_ROOT_PASSWORD=myTestPassword
